spring:
  application:
    name: src

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate

  sql:
    init:
      mode: never

auth:
  access-token-validity-seconds: 3600
  refresh-token-validity-seconds: 1209600
  cookie-secure: false    # should be true, false just for demo

media:
  propics:
    resolution-px: 480
    compression-ratio: 85

management:
  server:
    address: 127.0.0.1
    port: 8081
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
